language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install codecov
# command to run tests and style check
script:
  - export DJANGO_SETTINGS_MODULE=indiaelections.settings
  - export TW_CONSUMER_KEY='test'
  - export TW_CONSUMER_SECRET='test'
  - export TW_ACCESS_TOKEN='test'
  - export TW_ACCESS_TOKEN_SECRET='test'
  - export SENTRY_TOKEN='test'
  - export DB_NAME=''
  - export DB_USERNAME=''
  - export DB_PASSWORD=''
  - export DB_HOST=''
  - pytest
  - flake8 .
  - pytest --cov=core
after_success:
- codecov