language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
# command to run tests and style check
script:
  - pytest
  - flake8 .
  - pytest --cov=core