# Generated by Django 2.1.4 on 2018-12-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField()),
                ('cleaned_text', models.TextField()),
                ('sentiment', models.CharField(choices=[('p', 'positive'), ('n', 'negative'), ('e', 'neutral')], max_length=1)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
