# Generated by Django 2.1.4 on 2018-12-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='q',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
