# Generated by Django 2.1.4 on 2019-01-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tweet_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordcloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=200)),
            ],
        ),
    ]
