# Generated by Django 2.1.4 on 2019-01-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190114_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetstats',
            name='female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweetstats',
            name='male',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
