# Generated by Django 2.1.4 on 2019-01-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190122_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetstats',
            name='party',
            field=models.CharField(choices=[('u', 'upa'), ('n', 'nda')], default='', max_length=1),
        ),
    ]
