# Generated by Django 2.1.4 on 2019-02-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tweetstats_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=100)),
                ('party', models.CharField(choices=[('u', 'upa'), ('n', 'nda')], default='', max_length=1)),
            ],
        ),
    ]
