# Generated by Django 2.1.4 on 2019-02-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=100)),
                ('comment_words', models.TextField()),
            ],
        ),
    ]
