# Generated by Django 2.1.4 on 2019-02-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_commentwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetstats',
            name='comment_words',
        ),
    ]
