# Generated by Django 2.1.4 on 2019-02-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190220_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='q',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
