# Generated by Django 2.1.4 on 2019-02-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFrameEnabledSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='opinionpoll',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, unique=True),
        ),
    ]
