# Generated by Django 2.1.4 on 2019-02-27 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20190226_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinionpoll',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.Constituency'),
        ),
        migrations.AddField(
            model_name='opinionpoll',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.StateUnion'),
        ),
    ]
